### ISSUE TITLE
allele.adjusted.txt 文件列表是空的

### ISSUE THREAD

**Issue by NINGCHINA** [sc-zhang/AlleleFinder#1]
shengcheng 你好，我有一个4倍体物种，利用近源物种做参考，分析alllele，但是allele.adjusted.txt 文件列表是空的,只有一个表头。

运行命令如下：AlleleFinder -r DCP.fasta -d DCP.cds -f DCP.gff3 -c TCPA.cds -g TCPA.gff3 -n 4 -w work_dir/ -t 20

**Comment by NINGCHINA** [comment]
shengcheng。您那里有实例文件吗？ 感谢

**Comment by sc-zhang** [comment]
Make sure that the values of "Name" in "gene" line of gff3  file can match IDs in cds, if there is no "Name" attribute in gff3 file, then the  values of "ID" must match the IDs in cds file.

**Comment by zywen12** [comment]
张老师您好，我也遇到了类似的问题，用的您茶树的数据试验的，将cds文件的ID号和gff文件的ID号改为一样的，但是跑出来的结果依然是0，请问这是哪里出问题了。开始按原代码跑会出错，找不到01.mcscanx/xyz/xyz.html，将AlleleFinder文件第50行mcs_dir = "01.mcscanx/xyz/xyz.html"改为mcs_dir = "01.mcscanx/xyz"可以跑出来，没有报错，但结果文件都是0。

**Comment by sc-zhang** [comment]
@zywen12 Do not modify the mcs_dir in the AlleleFinder, because this folder is generated by MCScanX, and contains .html files of every single chromosomes, if the script could not find the path, it means the MCScanX did not finished normally, so you can run MCScanX manually with the xyz.cds and xyz.gff file generated by AlleleFinder, and check if the MCScanX can generate xyz.html or not.

**Comment by zywen12** [comment]
张老师您好，我的blastdb文件无法创建，生成是空的，手动执行makeblastdb报错：No volumes were created.
Error: mdb_env_open: Function not implemented。请问下这个怎么解决啊，谢谢~~

**Comment by zywen12** [comment]
张老师您好，我们现在分析遇到的问题是运行第一步run_MCScanX.py这个脚本，命令是python ~/AlleleFinder/bin/run_MCScanX.py ~/tea/Allelefinder/GWHASIX00000000.cds.fasta ~tea/Allelefinder/GWHASIX00000000.gff3 01.mcscanx 12 &> /dev/null对下载的cds文件只修改了OrigeneID改为了ID和gff文件的ID=CsTGY01G0000005a对应，gff文件未做任何处理，跑出来的xyz.collinearity文件collinear genes数是0，html文件也没有共线区块，生成的xyz.gff文件是这样的：NN01	CsTGY01G0000005a	1035778	1041388，xyz.blast文件取得却是GWHTASIX000001	GWHTASIX000001这个编号。我们又试了一下对cds文件只保留ID号>CsTGY01G0000005a，gff文件不做处理，得到的xyz.blast文件是取得唯一给出的ID编号CsTGY01G0000005a  CsTGY01G0000005a，但是却没有生成xyz.gff文件，也没有html文件。请问下张老师这是哪里出问题了，请张老师指点~

**Comment by zywen12** [comment]
张老师您好，我们现在分析遇到的问题是运行第一步run_MCScanX.py这个脚本，命令是python ~/AlleleFinder/bin/run_MCScanX.py ~/tea/Allelefinder/GWHASIX00000000.cds.fasta tea/Allelefinder/GWHASIX00000000.gff3 01.mcscanx 12 &> /dev/null对下载的cds文件只修改了OrigeneID改为了ID和gff文件的ID=CsTGY01G0000005a对应，gff文件未做任何处理，跑出来的xyz.collinearity文件collinear genes数是0，html文件也没有共线区块，生成的xyz.gff文件是这样的：NN01 CsTGY01G0000005a 1035778 1041388，xyz.blast文件取得却是GWHTASIX000001 GWHTASIX000001这个编号。我们又试了一下对cds文件只保留ID号>CsTGY01G0000005a，gff文件不做处理，得到的xyz.blast文件是取得唯一给出的ID编号CsTGY01G0000005a CsTGY01G0000005a，但是却没有生成xyz.gff文件，也没有html文件。请问下张老师这是哪里出问题了，请张老师指点~

**Comment by sc-zhang** [comment]
Here we require the annotation file gff3 and as I recognize the ”Name" in "gene" line before "ID" in the script, so if you extract cds with tools by genome file and gff3 file, the ID in cds may match the ID in the "CDS" line of gff3, then mismatch happened. 
So the first thing you need to do is check the ID of cds file can match the “Name" in the "gene" line of gff3 file, if not and it can partially match "ID" in "gene" line, you can replace "Name" to any other string in gff3 file with sed that make there no key named "Name", and then remove the suffix of ID in cds file to make the ID in cds match the ID in "gene" line of gff3.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 晚上9:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sc-zhang/AlleleFinder] allele.adjusted.txt 文件列表是空的 (Issue #1)





 
张老师您好，我们现在分析遇到的问题是运行第一步run_MCScanX.py这个脚本，命令是python ~/AlleleFinder/bin/run_MCScanX.py /tea/Allelefinder/GWHASIX00000000.cds.fasta tea/Allelefinder/GWHASIX00000000.gff3 01.mcscanx 12 &amp;&gt; /dev/null对下载的cds文件只修改了OrigeneID改为了ID和gff文件的ID=CsTGY01G0000005a对应，gff文件未做任何处理，跑出来的xyz.collinearity文件collinear genes数是0，html文件也没有共线区块，生成的xyz.gff文件是这样的：NN01 CsTGY01G0000005a 1035778 1041388，xyz.blast文件取得却是GWHTASIX000001 GWHTASIX000001这个编号。我们又试了一下对cds文件只保留ID号&gt;CsTGY01G0000005a，gff文件不做处理，得到的xyz.blast文件是取得唯一给出的ID编号CsTGY01G0000005a CsTGY01G0000005a，但是却没有生成xyz.gff文件，也没有html文件。请问下张老师这是哪里出问题了，请张老师指点
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zywen12** [comment]
张老师您好，还有一个问题要请教一下，就是我们用茶树21年NG的数据最后跑出来了等位基因的csv列表，表格有32755列，但是这个列表里大部分基因只有一个等位基因：CsTGY15G0001909b，而只有3134个基因含有2个或2个以上的等位基因，在脚本运行过程中并没有报错记录。而我们使用苹果的数据在运行第三步时总会有个报错Step3: Generating first allele table
[32m[16:26:55][0m 	Loading MCScanX results
[32m[16:26:57][0m 	Loading GMAP result
sh: line 1: 21549 Killed，然后继续运行，也能得到最后的等位基因csv表格，这个表格总共有33220列，大部分是有另一个相对应的基因的：Mdg_17A025450  [Mdg_17B023590，但A和B两个单倍型上的基因编号大部分却不对应，恳请张老师给予指点，谢谢！

**Comment by NINGCHINA** [comment]
We have solved the problem! By the way, I don't know why we set "p=4" as in the Gmap program. I also have 2 more questions that need to be answered. First, when checking the "allele.adjusted.txt" we found that several autopolyploids genes map to the same diploid genes, so how to handle those alleles? Second, we are interested in where do those alleles go, resulting in many empty alleles.

**Comment by sc-zhang** [comment]
@NINGCHINA For the first question, the p=4 means tetraploid. And for the other questions, the auto-polyploid genes which map to the same diploid genes means some of them are allele genes and the other ones are paralog genes.
