### ISSUE TITLE
Loading GMAP  result Error

### ISSUE THREAD

**Issue by gruit01** [sc-zhang/AlleleFinder#10]
Hello author,
When  I use the program, it error ,and i cannot find the problem.
step3:
Loading GMAP  result 
/utils/utils.py", line 382, in read_gff3
    chrn = re.findall(r'([A-Za-z]+\d+).*', data[0])[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Appreciate you suggestions!

Best

**Comment by sc-zhang** [comment]
The ID in reference genome should be like Chr01 or LG01, so this problem may caused by the exists of mitochondrion or chloroplast sequence in reference genome. To solve this problem, you can check the chromosome ID manually, and if the ID of sequence is not start with letters and end with numbers, just rename it.
