### ISSUE TITLE
运行疑问

### ISSUE THREAD

**Issue by markme123** [sc-zhang/AlleleFinder#2]
张老师，我看参数里面有ref，是必须用1个基因组做参考才能做吗，后面的多倍体 cds ,是多套的cds 融合在一起吗。

**Comment by sc-zhang** [comment]
Yes, it need a reference genome for constructing allele table, and the cds from polyploid should contain all cds sequences.

**Comment by markme123** [comment]
张老师，如果我没有参考能用多倍体其中的一套做参考吗。另外基因组里面有scaffold 可以运行吗

**Comment by markme123** [comment]
您在页面上写的 额外部分pull_down_paralog.py 看不懂，请您解惑

**Comment by markme123** [comment]
allele.adjusted.allele.stat    allele.adjusted.genes.stat  他们代表的意义是什么呢

**Comment by sc-zhang** [comment]
- For the first question, the answer is yes. The answer of the second question is yes, but genes on scaffolds will be dropped. 
- Because of the identification of allelic genes is based on gmap and blast, sometimes you may found that there are too many genes are identified as paralogs, for this reason, the pull_down_paralog.py will mark them as new alleles.
- As each line in allele table contain a gene and its allelic genes, that the allele.stat count the genes on each haplotype which were not marked as paralogs or tandems, and for the polyploid genome, we count the gene with 0 to n-1 allelic genes on each chromosome and store it in the genes.stat.

**Comment by markme123** [comment]
在结果表allele.adjusted.tx中  CindChr2AG00499510.1-P  CindChr2AG00499510.1-T   这两种后缀的意义是什么呢

**Comment by sc-zhang** [comment]
P means paralog and T means tandem
